# Generated by Django 4.1.6 on 2023-02-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lib", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autor",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="дата создания"),
        ),
        migrations.AlterField(
            model_name="autor",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="дата редактирования"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="autor",
            field=models.ManyToManyField(
                blank=True, to="lib.autor", verbose_name="автор"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="дата создания"),
        ),
        migrations.AlterField(
            model_name="book",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="дата редактирования"
            ),
        ),
        migrations.AlterField(
            model_name="reader",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="дата создания"),
        ),
        migrations.AlterField(
            model_name="reader",
            name="updated",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="дата редактирования"
            ),
        ),
    ]
