# Generated by Django 4.1.6 on 2023-03-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lib", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reader",
            name="phone",
            field=models.BigIntegerField(verbose_name="номер телефона"),
        ),
    ]
