# Generated by Django 4.1.6 on 2023-02-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lib", "0002_alter_autor_created_at_alter_autor_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="autor",
            field=models.ManyToManyField(to="lib.autor", verbose_name="автор"),
        ),
        migrations.AlterField(
            model_name="book",
            name="description",
            field=models.TextField(max_length=255, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="reader",
            name="active_book",
            field=models.ManyToManyField(
                blank=True, to="lib.book", verbose_name="активные книги"
            ),
        ),
    ]
